/**
 * Список страниц для скриншотов: path — маршрут Next.js, fileName — имя файла без расширения в `screens/`.
 * Дополняйте по мере появления новых экранов.
 */
export const pagesToScreenshot: Array<{ path: string; fileName: string }> = [
  { path: "/", fileName: "01-home" },
  { path: "/banking", fileName: "02-banking" },
  { path: "/banking/cash", fileName: "03-banking-cash" },
  { path: "/expenses/quick", fileName: "04-expenses-quick" },
  { path: "/invoices", fileName: "05-invoices" },
  { path: "/invoices/new", fileName: "06-invoices-new" },
  { path: "/counterparties", fileName: "07-counterparties" },
  { path: "/counterparties/new", fileName: "08-counterparties-new" },
  { path: "/inventory/purchase", fileName: "09-inventory-purchase" },
  { path: "/inventory", fileName: "10-inventory" },
  { path: "/products", fileName: "11-products" },
  { path: "/products/new", fileName: "12-products-new" },
  { path: "/inventory/transfer", fileName: "13-inventory-transfer" },
  { path: "/inventory/adjustments", fileName: "14-inventory-adjustments" },
  { path: "/inventory/audits", fileName: "15-inventory-audits" },
  { path: "/manufacturing", fileName: "16-manufacturing" },
  { path: "/manufacturing/recipe", fileName: "17-manufacturing-recipe" },
  { path: "/manufacturing/release", fileName: "18-manufacturing-release" },
  { path: "/employees", fileName: "19-employees" },
  { path: "/employees/new", fileName: "20-employees-new" },
  { path: "/hr/positions", fileName: "21-hr-positions" },
  { path: "/hr/structure", fileName: "22-hr-structure" },
  { path: "/hr/timesheet", fileName: "23-hr-timesheet" },
  { path: "/payroll", fileName: "24-payroll" },
  { path: "/reporting", fileName: "25-reporting" },
  { path: "/reporting/receivables", fileName: "26-reporting-receivables" },
  { path: "/reporting/reconciliation", fileName: "27-reporting-reconciliation" },
  { path: "/reporting/aging", fileName: "28-reporting-aging" },
  { path: "/reporting/tax-export", fileName: "29-reporting-tax-export" },
  { path: "/fixed-assets", fileName: "30-fixed-assets" },
  { path: "/fixed-assets/new", fileName: "31-fixed-assets-new" },
  { path: "/settings/team", fileName: "32-settings-team" },
  { path: "/settings/audit", fileName: "33-settings-audit" },
  { path: "/settings/mapping", fileName: "34-settings-mapping" },
  { path: "/settings/subscription", fileName: "35-settings-subscription" },
  { path: "/companies", fileName: "36-companies" },
  { path: "/inventory/audit", fileName: "37-inventory-audit" },
  { path: "/inventory/audit/new", fileName: "38-inventory-audit-new" },
  { path: "/admin/billing", fileName: "39-admin-billing" },
  { path: "/admin/subscription", fileName: "40-admin-subscription" },
  { path: "/admin/payment-history", fileName: "41-admin-payment-history" },
  { path: "/super-admin", fileName: "42-super-admin" },
  { path: "/super-admin/translations", fileName: "43-super-admin-translations" },
];
